language: go

os:
- linux
- osx

env:
- GO111MODULE=on 

go:
- "1.12"

git:
  depth: 1

go_import_path: sigs.k8s.io/cli-utils

before_install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.17.1

install:
  -

script:
  - TRACE=1 ./scripts/check-everything.sh

# TBD. Suppressing for now.
notifications:
  email: false